### ISSUE TITLE
More info link in Server info block frontpage - error

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#41]
When i click More Info Link in the Frontpage in the Server info block i receive folllowing error

Warning: include(templates/blizzlike/server/server.info.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 249 Warning: include(): Failed opening 'templates/blizzlike/server/server.info.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 249

**Comment by paintballrefjosh** [comment]
Yes this is a bad link.  I'll have a fix out for it tonight.

**Comment by paintballrefjosh** [comment]
This should now be fixed in the bug-fixes branch.  3 files were updated:

inc/frontpage/frontpage.index.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/frontpage/frontpage.index.php)
inc/server/server.statistic.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/server/server.statistic.php)
templates/blizzlike/body_right.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/templates/blizzlike/body_right.php)

**Comment by Cubansephiroth** [comment]
Yep, working as intended, thanks.. Closing...
